### ISSUE TITLE
SSR with Universal

### ISSUE THREAD

**Issue by coenraadf** [ribalnasr/ng-flamelink#11]
I am building a project using Flamelink and Angular, and love your implementation of the Flamelink SDK using @angular/fire.

I need to do SSR and Pre-rendering using Angular Universal, and need to use the firebase-admin package. Does ng-flamelink support this implementation? If so, how would I go about in using an admin firebaseApp setup?

**Comment by ribalnasr** [comment]
The library works normally with Angular Universal however I tested it with
a client side firebaseApp. using this method I always use a conditional
statement to make sure the platform is browser using angular's
isPlatformBrowser() before using storage related method and/or population
media fields.

I don't believe it's good practice to use it with firebase admin even with
SSR since you'll exposing the admin sdk to the client-side.

**Comment by coenraadf** [comment]
I see. My site basically has 3 queries in total, that gets quite complex and all have storage population sections in them, which I need for SSR and pre-rendering. I could run separate queries for server and browser, but then I will have an issue with the images for SEO and OpenGraph.

Will the library work with me passing in a firebase-admin session, or would I need to do some alternative workarounds for this?

**Comment by ribalnasr** [comment]
for the seo i don't think you need the photos as for the opengraph you will need to create a firebase function to get the images urls. at least that's what i do. am open to better suggestions. 
actually this issue is not directly related to ng-flamelink rather than the flamelink-js-sdk. maybe we should move this conversation there?
